# Project information
site_name: lakeFS Documentation
site_url: https://docs.lakefs.io/
site_author: treeverse
site_description: Open Source Data Version Control for Data Lakes and Data Lakehouses

# Repository
repo_url: https://github.com/treeverse/lakeFS
repo_name: treeverse/lakeFS
edit_uri: edit/main/docs/ # Link to edit page in GitHub

# Copyright
copyright: Copyright &copy; 2020 - present treeverse

# Configuration
docs_dir: 'docs_mkdocs' # Will be created in the next step

# Theme
theme:
  name: material
  logo: assets/logo.svg # Will be moved in a later step
  favicon: assets/favicon.ico # Will be moved/checked in a later step
  features:
    - navigation.tabs
    # - navigation.tabs.sticky # Optional: if top nav should stick
    - navigation.sections
    - navigation.expand
    - navigation.top # Back to top button
    - search.suggest # Search autocompletion
    - search.highlight # Search term highlighting
    - content.code.copy # Copy button for code blocks
    - content.code.annotate # Code annotations
    # - toc.integrate # Show TOC on the left, rather than right. Consider based on preference.
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: lime # Changed accent for dark mode for better visibility if needed
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Galano Grotesque # Will need to ensure font files are available
    code: Roboto Mono
  icon:
    repo: fontawesome/brands/github

# Plugins
plugins:
  - search # Built-in search, explicitly listed
  - awesome-pages # For navigation generation from directory structure if needed later
  - redirects: # For handling old Jekyll links
      redirect_maps: {} # Will be populated later

# Markdown extensions
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true # Adds anchor links to headings
      slugify: !!python/name:pymdownx.slugs.uslugify # Unicode aware slugsin

# Extra Customization (will be populated later if needed)
extra_css: []
extra_javascript: []

# Navigation (will be defined in a later step, can be auto-generated by awesome-pages)
# nav:
#   - Home: index.md

nav:
  - Home: index.md
  - Quickstart: quickstart/index.md
  - Understand lakeFS: understand/index.md
  - How-To Guides: howto/index.md
  - Integrations: integrations/index.md
  - Reference: reference/index.md
  - Security: security/index.md
  - Cloud: cloud/index.md
  - Enterprise: enterprise/index.md
  - Experimental: experimental/index.md
  - Project: project/index.md
  - Posts: posts/index.md
  - Slack Community: slack/index.md
