name: Nessie
on:
  workflow_dispatch:

jobs:
  nessie:
    name: Build Docker image
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup UI (node 10)
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: Setup Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.16.2
        id: go
      - name: Generate code
        run: |
          make gen
      - name: Build image
        run: docker build -t treeverse/lakefs-next --build-arg VERSION=${{ steps.version.outputs.tag }} .
      - name: Test lakeFS local
        env:
          TAG: latest
          REPO: treeverse
          LAKEFS_STATS_ENABLED: "false"
          LAKEFS_BLOCKSTORE_TYPE: local
          LAKEFS_GATEWAYS_S3_DOMAIN_NAME: s3.local.lakefs.io:8000
          NESSIE_TEST_DATA_ACCESS: false,false
          NESSIE_STORAGE_NAMESPACE: local://nessie-system-testing
        run: docker-compose -f nessie/ops/docker-compose.yaml up --exit-code-from=nessie
      - name: lakeFS Logs on s3 failure
        if: ${{ failure() }}
        continue-on-error: true
        run: docker-compose -f nessie/ops/docker-compose.yaml logs --tail=1000 lakefs

